version: "3.9"
services:
    test:
        build:
          dockerfile: Dockerfile-test  
          context: .          

    api:
        build:
          dockerfile: Dockerfile-api  
          context: .     
        ports:
            - "5001:5001"
